[options]
addons_path = /home/victor/odoo/odoo19/odoo/addons,
            /home/victor/odoo/odoo19/addons,
            # /home/victor/odoo/external-addons/19,
            /home/victor/projects/tkg/development/tkg-odoo/addons/,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/reporting-engine,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-analytic,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-budgeting,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-financial-reporting,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-financial-tools,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-invoicing,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-payment,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/account-reconcile,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/server-ux,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/oca/mis-builder,
            /home/victor/projects/tkg/development/tkg-odoo/external-addons/triton-odoo,
admin_passwd = 213201
db_host = localhost
db_user = odoo
db_password = odoo
http_port = 8019
limit_time_cpu = 600
limit_time_real = 1200
# workers = 2