[options]
addons_path = /home/victor/odoo/odoo19+e,
              /home/victor/projects/tkg/development/odoo19/addons/,
admin_passwd = 213201
db_host = localhost
db_user = odoo
db_password = odoo
http_port = 8019
# workers = 2